version: "3.8"
services:
    # ATTENTION!!! don't use it in production, use 1 loki for reading, 1 loki for writing 
    # and a minio for data
    loki:
        image: grafana/loki:2.8.0
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - back_net
#    promtail:
#        image: grafana/promtail:2.8.0
#        volumes:
#            - /var/log:/var/log
#        command: -config.file=/etc/promtail/config.yml
#        networks:
#            - back_net
    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        networks:
          - back_net
          - bridge_net
        environment:
            - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        entrypoint:
            - sh
            - -euc
            - |
                mkdir -p /etc/grafana/provisioning/datasources
                cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
                apiVersion: 1
                datasources:
                    - name: Loki
                type: loki
                orgId: 1
                url: http://loki:3100
                basicAuth: false
                isDefault: true
                version: 1
                editable: true
                EOF
                /run.sh
networks:
    back_net:
        external: false
    bridge_net:
        driver: bridge
